// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var api, ensureLoggedIn, fql, resp, slice;
    slice = Array.prototype.slice;
    ensureLoggedIn = function(base) {
      return function() {
        var args;
        args = slice.call(arguments);
        return FB.getLoginStatus(function() {
          return base.apply(void 0, args);
        }, true);
      };
    };
    resp = function(req, route, callback, errback) {
      return function(res) {
        var errorMsg;
        if (res && !res.error) {
          return callback(res);
        } else {
          if (res) {
            errorMsg = "[FB Error] " + res.error.type + " : " + res.error.message;
          } else {
            errorMsg = "[FB Error] Unknown error";
          }
          return errback(errorMsg, {
            result: res,
            request: req
          });
        }
      };
    };
    api = ensureLoggedIn(function(req, route, callback, errback) {
      var path;
      path = req.path.replace(/^\/?facebook\//, '');
      return FB.api(path, req.method, req.params, resp(req, route, callback, function(msg, res) {
        res.time = new Date();
        return callback(res);
      }));
    });
    fql = ensureLoggedIn(function(req, route, callback, errback) {
      return FB.api({
        method: 'fql.query',
        query: req.params.query
      }, resp(req, route, callback, errback));
    });
    return {
      config: {
        require: {
          paths: {
            facebook: "https://connect.facebook.net/en_US/all"
          },
          shim: {
            facebook: {
              exports: 'FB'
            }
          }
        }
      },
      init: function(env) {
        var dfd;
        dfd = env.core.data.deferred();
        FB.init(env.config.services.facebook);
        FB.getLoginStatus(dfd.resolve);
        env.core.services.add([
          {
            path: "/facebook/fql",
            handler: fql
          }
        ]);
        env.core.services.add([
          {
            path: "/facebook/*path",
            handler: api
          }
        ]);
        return dfd;
      }
    };
  });

}).call(this);
