// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore'], function($, _) {
    return function(env) {
      var config, handler,
        _this = this;
      config = env.config.services.hull;
      handler = function(req, route, callback, errback) {
        var path, req_data, request, url;
        path = req.path.replace(/^\/?hull\//, '');
        if (path[0] === "/") {
          path = path.substring(1);
        }
        url = config.baseUrl + "/" + path;
        if (req.method.toLowerCase() === 'delete') {
          req_data = JSON.stringify(req.params || {});
        } else {
          req_data = req.params;
        }
        request = $.ajax({
          url: url,
          type: req.method,
          data: req_data,
          headers: {
            'Hull-App-Id': config.appId
          }
        });
        request.done(function(res) {
          return callback(res || {});
        });
        request.fail(errback);
      };
      return {
        init: function(env) {
          return env.core.services.add([
            {
              path: 'hull/*path',
              handler: handler
            }
          ]);
        }
      };
    };
  });

}).call(this);
