// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var authenticating;
    authenticating = false;
    return function(env) {
      var core, sandbox;
      sandbox = env.sandbox;
      core = env.core;
      return {
        init: function() {
          sandbox.authenticating = function() {
            return authenticating;
          };
          sandbox.authComplete = function() {
            var dfd, me, providerName;
            try {
              if (authenticating.state() !== 'pending') {
                return;
              }
              providerName = authenticating.providerName;
              dfd = authenticating;
              me = sandbox.data.api.model('me');
              dfd.done(function() {
                return me.trigger('change');
              });
              return me.fetch({
                success: dfd.resolve,
                error: dfd.reject,
                silent: true
              });
            } catch (err) {
              return console.error("Error on auth promise resolution", err);
            } finally {
              authenticating = false;
            }
          };
          sandbox.login = function(providerName, opts, callback) {
            var auth_params, auth_url;
            if (callback == null) {
              callback = function() {};
            }
            if (authenticating) {
              return;
            }
            providerName = providerName && providerName.toLowerCase();
            if (!providerName) {
              return;
            }
            authenticating = sandbox.data.deferred();
            authenticating.providerName = providerName;
            if (_.isFunction(callback)) {
              authenticating.done(callback);
            }
            auth_url = "" + env.config.orgUrl + "/auth/" + (providerName.toLowerCase());
            auth_params = opts || {};
            auth_params.app_id = env.config.appId;
            auth_params.callback_url = env.config.callback_url || document.location.toString();
            auth_params.auth_referer = document.location.toString();
            auth_url += "?" + ($.param(auth_params));
            window.open(auth_url, "_auth", 'location=0,status=0,width=990,height=600');
            return authenticating;
          };
          return sandbox.logout = function(callback) {
            var dfd;
            if (callback == null) {
              callback = function() {};
            }
            dfd = sandbox.data.api('hull/logout');
            dfd.done(function() {
              sandbox.data.api.model('me').clear();
              sandbox.data.api.model.clearAll();
              if (_.isFunction(callback)) {
                return callback();
              }
            });
            return dfd;
          };
        }
      };
    };
  });

}).call(this);
