// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var catchAll, rpc;
    rpc = null;
    catchAll = function(res) {
      console.warn("CatchAll Handler: ", res);
      return res;
    };
    return function(env) {
      return {
        config: {
          require: {
            paths: {
              'easyXDM': 'easyXDM/easyXDM',
              'route-recognizer': 'route-recognizer/dist/route-recognizer.amd'
            },
            shim: {
              easyXDM: {
                exports: 'easyXDM'
              }
            }
          }
        },
        init: function(env) {
          var Router, core, onRemoteMessage;
          core = env.core;
          Router = require('route-recognizer');
          core.services = new Router;
          onRemoteMessage = function(req, callback, errback) {
            var route, routes;
            if (!req.path) {
              throw new Error("Path not recognized " + (JSON.stringify(req)));
            }
            window.__router = core.services;
            routes = core.services.recognize(req.path);
            if (routes && (route = routes[0])) {
              console.warn("[ROUTE] " + (req.method.toUpperCase()) + ": " + req.path, req.params);
              return route.handler(req, route, callback, errback);
            } else {
              return errback(catchAll(req));
            }
          };
          rpc = new easyXDM.Rpc({}, {
            remote: {
              message: {},
              ready: {}
            },
            local: {
              message: onRemoteMessage
            }
          });
          return true;
        },
        afterAppStart: function() {
          return rpc.ready(env.config.data);
        }
      };
    };
  });

}).call(this);
