// Generated by CoffeeScript 1.3.3
(function() {

  define(['components/aura-express/lib/aura'], function(Aura) {
    var hull, myApp;
    hull = null;
    myApp = {
      name: 'myApp',
      afterAppStart: function(env) {
        return window.Hull = env.core.createSandbox();
      }
    };
    try {
      if (window.opener && window.opener.Hull) {
        try {
          window.opener.Hull.emit("hull.authComplete");
          return window.close();
        } catch (e) {
          console.warn("Error: " + e);
        }
      }
    } catch (e2) {
      console.warn("Error: " + e2);
    }
    return function(config) {
      if (hull && hull.app) {
        return hull;
      }
      hull = {
        config: config
      };
      hull.app = Aura(config);
      hull.app.use('aura-extensions/aura-handlebars').use('aura-extensions/aura-backbone').use('lib/client/api').use('lib/client/auth').use('lib/client/templates').use('lib/client/widget').use(myApp).start({
        widgets: 'body'
      });
      return hull;
    };
  });

}).call(this);
