// Generated by CoffeeScript 1.3.3
(function() {

  define(['components/aura-express/lib/aura'], function(Aura) {
    var Hull, hull;
    hull = null;
    Hull = function(config) {
      if (hull && hull.app) {
        return hull;
      }
      hull = {
        config: config
      };
      hull.app = Aura(config);
      hull.app.use('extensions/aura-handlebars').use('extensions/aura-backbone').use('lib/ext/api').use('lib/ext/auth').use('lib/ext/widget').start({
        widgets: 'body'
      });
      return hull;
    };
    window.Hull = Hull;
    return Hull;
  });

}).call(this);
