// Generated by CoffeeScript 1.3.3
(function() {

  define(['components/aura-express/lib/aura'], function(Aura) {
    var Hull, hull;
    hull = null;
    Hull = function(config) {
      var serviceConfig, serviceName, _ref;
      if (hull && hull.app) {
        return hull;
      }
      hull = {
        config: config
      };
      config.debug = true;
      hull.app = Aura(config);
      hull.app.use('lib/remote/services');
      _ref = config.services;
      for (serviceName in _ref) {
        serviceConfig = _ref[serviceName];
        hull.app.use("lib/remote/services/" + serviceName + "-service");
      }
      hull.app.start();
      return hull;
    };
    window.Hull = Hull;
    return Hull;
  });

}).call(this);
