// var keyMirror = require('react/lib/keyMirror');
// module.exports = keyMirror({
//   CLEAR_HEADER: null,
//   SET_HEADER: null,
//   SET_TOKEN_HEADER: null,
//   SET_APP_ID_HEADER:null,
//   SET_USER_ID_HEADER: null,
//   UPDATE_CLIENT_CONFIG: null,
//   UPDATE_REMOTE_CONFIG: null,
//   CLEAR_USER: null,
//   UPDATE_USER: null,
//   UPDATE_USER_IF_ME: null,
//   CLEAR_SETTINGS: null,
//   UPDATE_SETTINGS: null
// });
module.exports = {
  CLEAR_HEADER:'CLEAR_HEADER',
  SET_HEADER:'SET_HEADER',
  SET_TOKEN_HEADER:'SET_TOKEN_HEADER',
  SET_APP_ID_HEADER:'SET_APP_ID_HEADER',
  SET_USER_ID_HEADER:'SET_USER_ID_HEADER',
  UPDATE_CLIENT_CONFIG:'UPDATE_CLIENT_CONFIG',
  UPDATE_REMOTE_CONFIG:'UPDATE_REMOTE_CONFIG',
  CLEAR_USER:'CLEAR_USER',
  UPDATE_USER:'UPDATE_USER',
  UPDATE_USER_IF_ME:'UPDATE_USER_IF_ME',
  CLEAR_SETTINGS:'CLEAR_SETTINGS',
  UPDATE_SETTINGS:'UPDATE_SETTINGS'
};
