module.exports = {
  CLEAR_HEADER:'CLEAR_HEADER',
  SET_HEADER:'SET_HEADER',
  SET_TOKEN_HEADER:'SET_TOKEN_HEADER',
  SET_APP_ID_HEADER:'SET_APP_ID_HEADER',
  UPDATE_CLIENT_CONFIG:'UPDATE_CLIENT_CONFIG',
  UPDATE_REMOTE_CONFIG:'UPDATE_REMOTE_CONFIG',
  UPDATE_SERVICES:'UPDATE_SERVICES',
  CLEAR_USER:'CLEAR_USER',
  UPDATE_USER:'UPDATE_USER'
};
