'use strict';
/* global require */

module.exports = {
  compact: require('lodash/compact'),
  uniq: require('lodash/uniq'),
  size: require('lodash/size'),
  includes: require('lodash/includes'),
  reject: require('lodash/reject'),
  toArray: require('lodash/toArray'),
  defaults: require('lodash/defaults'),
  isElement: require('lodash/isElement'),
  each: require('lodash/each'),
  partition: require('lodash/partition'),
  every: require('lodash/every'),
  indexOf: require('lodash/indexOf'),
  isEmpty: require('lodash/isEmpty'),
  throttle: require('lodash/throttle'),
  isArray: require('lodash/isArray'),
  isEqual: require('lodash/isEqual'),
  isFunction: require('lodash/isFunction'),
  isObject: require('lodash/isObject'),
  isString: require('lodash/isString'),
  isUndefined: require('lodash/isObject'),
  keys: require('lodash/keys'),
  map: require('lodash/map'),
  find: require('lodash/find'),
  filter: require('lodash/filter'),
  values: require('lodash/values'),
  omit: require('lodash/omit'),
  pick: require('lodash/pick'),
  reduce: require('lodash/reduce'),
  some: require('lodash/some'),
  fromPairs: require('lodash/fromPairs')
};
